apiVersion: v2
name: argocd
description: Custom chart form old ingress controller from k8s
version: 1.0.0
appVersion: v4.14.3
dependencies:
  - name: ingress-nginx
    repository: https://kubernetes.github.io/ingress-nginx
    version: 4.14.3
